[package]
name = "premade_ports"
version = "0.1.0"
edition = "2024"

[dependencies]
quinn = { workspace = true }
framework = { path = "../framework" }


[[example]]
name = "quinn_simple"
path = "examples/quinn/simple.rs"

[[example]]
name = "quinn_simple_with_mock_auth"
path = "examples/quinn/simple_with_mock_auth.rs"
